/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- FIND TOTAL CUSTOMERS BY COUNTRY
SELECT country, COUNT(customer_id) AS number_of_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY number_of_customers DESC

-- FIND TOTAL CUSTOMERS BY GENDER
SELECT gender, COUNT(customer_id) AS number_of_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY number_of_customers DESC

-- FIND TOTAL PRODUCTS BY CATEGORY
SELECT category, COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- WHAT IS THE AVARAGE COSTS IN EACH CATEGORY
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- WHAT IS THE TOTAL REVENUE GENERATE FOR EACH CATEGORY
SELECT * FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key

SELECT p.category, SUM(f.sales_amount) AS total_revenue 
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- FIND TOTAL REVENUE IS GENERATED BY EACH CUSTOMER 
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- WHAT IS THE DISTRIBUTION OF SOLD ITEM ACROSS COUNTRIES
SELECT c.country, SUM(f.quantity) AS total_sales 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sales DESC

